apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-latest-version
  namespace: argocd
spec:
  destination:
    namespace: helm-chart-latest-version
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    chart: ingress-nginx
    repoURL: "https://kubernetes.github.io/ingress-nginx"
    targetRevision: '*'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
