apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-helm-chart
  namespace: argocd
spec:
  destination:
    namespace: helm-chart
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    chart: sealed-secrets
    repoURL: "https://bitnami-labs.github.io/sealed-secrets"
    targetRevision: 1.*
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
