apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diffing-customization
  namespace: argocd
spec:
  destination:
    namespace: diffing-customization
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/PavanKarthik12/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    ignoreDifference:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
