apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-git-track
  namespace: argocd
spec:
  description: An application which takes a tag of repo as source
  destination:
    namespace: git-track
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    path: guestbook
    repoURL: "https://github.com/PavanKarthik12/argocd-example-apps.git"
    targetRevision: v1
    directory:
      recursive: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
