apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-failOnSharedResource-one
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
