apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: test-1
    server: "https://kubernetes.default.svc"
  project: whitelist-project
  source:
    path: helm-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
      valueFiles: 
      - values.yaml
      - values-production.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
