apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiple-sources
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: redis
      repoURL: "https://charts.bitnami.com/bitnami"
      targetRevision: 17.10.2
    - chart: prometheus-redis-exporter
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 5.3.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
