apiVersion: v1
kind: Secret
metadata:
  name: private-repo-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  stringData:
    type: git
    url: https://github.com/PavanKarthik12/argo-cd-app-1.git
    pasword: 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
    username: argo-token1 













