apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-with-role
  namespace: argocd
spec:
  description: project-with-role description
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  roles:
    - name: ci-role
      description: sync privilliges for project-with-role
      policies:
      - p,proj:project-with-role:ci-role,applications,sync,project-with-role/*,allow
          
status: {}