apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-phases
  namespace: argocd
spec:
  destination:
    namespace: sync-phases
    server: "https://kubernetes.default.svc"
  project: demo-project
  source:
    path: sync-phases
    repoURL: "https://github.com/PavanKarthik12/argocd-example-apps.git"
    targetRevision: master
  syncPolicy: 
    automated: {}
    syncOptions:
      - CreateNamespace=true
